In [1]:
import pandas as pd
from category_encoders import HashingEncoder

In [2]:
df = pd.read_csv('../datos/procesados/adult_limpio.csv')

In [3]:
df['income'] = df['income'].map({'<=50K': 0, '>50K': 1})

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48789 entries, 0 to 48788
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48789 non-null  int64
 1   workclass        48789 non-null  str
 2   fnlwgt           48789 non-null  int64
 3   education        48789 non-null  str
 4   educational-num  48789 non-null  int64
 5   marital-status   48789 non-null  str
 6   occupation       48789 non-null  str
 7   relationship     48789 non-null  str
 8   race             48789 non-null  str
 9   gender           48789 non-null  str
 10  capital-gain     48789 non-null  int64
 11  capital-loss     48789 non-null  int64
 12  hours-per-week   48789 non-null  int64
 13  native-country   48789 non-null  str
 14  income           48789 non-null  int64
dtypes: int64(7), str(8)
memory usage: 5.6 MB

# ONE HOT ENCODING

In [5]:
df_ohe = pd.get_dummies(df, dtype=int)

In [6]:
df_ohe.head()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native-country_Portugal,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia
0,25,226802,7,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,38,89814,9,0,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,28,336951,12,0,0,40,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
3,44,160323,10,7688,0,40,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,18,103497,10,0,0,30,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [7]:
df_ohe.info()

<class 'pandas.DataFrame'>
RangeIndex: 48789 entries, 0 to 48788
Columns: 106 entries, age to native-country_Yugoslavia
dtypes: int64(106)
memory usage: 39.5 MB

In [8]:
df_ohe.columns.tolist()

['age',
 'fnlwgt',
 'educational-num',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'income',
 'workclass_Federal-gov',
 'workclass_Local-gov',
 'workclass_Never-worked',
 'workclass_Private',
 'workclass_Self-emp-inc',
 'workclass_Self-emp-not-inc',
 'workclass_State-gov',
 'workclass_Without-pay',
 'education_10th',
 'education_11th',
 'education_12th',
 'education_1st-4th',
 'education_5th-6th',
 'education_7th-8th',
 'education_9th',
 'education_Assoc-acdm',
 'education_Assoc-voc',
 'education_Bachelors',
 'education_Doctorate',
 'education_HS-grad',
 'education_Masters',
 'education_Preschool',
 'education_Prof-school',
 'education_Some-college',
 'marital-status_Divorced',
 'marital-status_Married-AF-spouse',
 'marital-status_Married-civ-spouse',
 'marital-status_Married-spouse-absent',
 'marital-status_Never-married',
 'marital-status_Separated',
 'marital-status_Widowed',
 'occupation_Adm-clerical',
 'occupation_Armed-Forces',
 'occupation_Craft-repair',
 'occupation_Exec-managerial',
 'occupation_Farming-fishing',
 'occupation_Handlers-cleaners',
 'occupation_Machine-op-inspct',
 'occupation_Other-service',
 'occupation_Priv-house-serv',
 'occupation_Prof-specialty',
 'occupation_Protective-serv',
 'occupation_Sales',
 'occupation_Tech-support',
 'occupation_Transport-moving',
 'relationship_Husband',
 'relationship_Not-in-family',
 'relationship_Other-relative',
 'relationship_Own-child',
 'relationship_Unmarried',
 'relationship_Wife',
 'race_Amer-Indian-Eskimo',
 'race_Asian-Pac-Islander',
 'race_Black',
 'race_Other',
 'race_White',
 'gender_Female',
 'gender_Male',
 'native-country_Cambodia',
 'native-country_Canada',
 'native-country_China',
 'native-country_Columbia',
 'native-country_Cuba',
 'native-country_Dominican-Republic',
 'native-country_Ecuador',
 'native-country_El-Salvador',
 'native-country_England',
 'native-country_France',
 'native-country_Germany',
 'native-country_Greece',
 'native-country_Guatemala',
 'native-country_Haiti',
 'native-country_Holand-Netherlands',
 'native-country_Honduras',
 'native-country_Hong',
 'native-country_Hungary',
 'native-country_India',
 'native-country_Iran',
 'native-country_Ireland',
 'native-country_Italy',
 'native-country_Jamaica',
 'native-country_Japan',
 'native-country_Laos',
 'native-country_Mexico',
 'native-country_Nicaragua',
 'native-country_Outlying-US(Guam-USVI-etc)',
 'native-country_Peru',
 'native-country_Philippines',
 'native-country_Poland',
 'native-country_Portugal',
 'native-country_Puerto-Rico',
 'native-country_Scotland',
 'native-country_South',
 'native-country_Taiwan',
 'native-country_Thailand',
 'native-country_Trinadad&Tobago',
 'native-country_United-States',
 'native-country_Vietnam',
 'native-country_Yugoslavia']

In [9]:
df_ohe.to_csv('../datos/procesados/adult_ohe.csv', index=False)

# COUNT ENCODING

Frecuencia absoluta

In [10]:
df_count = df.copy()

In [11]:
cat_cols = col_categoricas = ['workclass', 'education', 'marital-status', "occupation", "relationship", "race", "gender", "native-country"]

for col in cat_cols:
    freq = df_count[col].value_counts()
    df_count[col] = df_count[col].map(freq)

In [25]:
df_count.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,36654,226802,1812,7,16081,3017,7568,4683,32614,0,0,40,44647,0
1,38,36654,89814,15770,9,22366,1485,19703,41713,32614,0,0,50,44647,0
2,28,3136,336951,1601,12,22366,982,19703,41713,32614,0,0,40,44647,1
3,44,36654,160323,10862,10,22366,3017,19703,4683,32614,7688,0,40,44647,1
4,18,36654,103497,10862,10,16081,8969,7568,41713,16175,0,0,30,44647,0

In [ ]:
df_count.info()

<class 'pandas.DataFrame'>
RangeIndex: 48789 entries, 0 to 48788
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48789 non-null  int64
 1   workclass        48789 non-null  int64
 2   fnlwgt           48789 non-null  int64
 3   education        48789 non-null  int64
 4   educational-num  48789 non-null  int64
 5   marital-status   48789 non-null  int64
 6   occupation       48789 non-null  int64
 7   relationship     48789 non-null  int64
 8   race             48789 non-null  int64
 9   gender           48789 non-null  int64
 10  capital-gain     48789 non-null  int64
 11  capital-loss     48789 non-null  int64
 12  hours-per-week   48789 non-null  int64
 13  native-country   48789 non-null  int64
 14  income           48789 non-null  int64
dtypes: int64(15)
memory usage: 5.6 MB

In [ ]:
df_count.to_csv('../datos/procesados/adult_count.csv')

frecuencia relativa

In [23]:
df_count_norm = df_count.copy()

In [24]:
filas = len(df_count_norm)
for col in cat_cols:
    df_count_norm[col] = df_count_norm[col] / filas

In [26]:
df_count_norm.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,0.751276,226802,0.037140,7,0.329603,0.061838,0.155117,0.095985,0.66847,0,0,40,0.915104,0
1,38,0.751276,89814,0.323229,9,0.458423,0.030437,0.403841,0.854967,0.66847,0,0,50,0.915104,0
2,28,0.064277,336951,0.032815,12,0.458423,0.020127,0.403841,0.854967,0.66847,0,0,40,0.915104,1
3,44,0.751276,160323,0.222632,10,0.458423,0.061838,0.403841,0.095985,0.66847,7688,0,40,0.915104,1
4,18,0.751276,103497,0.222632,10,0.329603,0.183832,0.155117,0.854967,0.33153,0,0,30,0.915104,0

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48789 entries, 0 to 48788
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48789 non-null  int64
 1   workclass        48789 non-null  str
 2   fnlwgt           48789 non-null  int64
 3   education        48789 non-null  str
 4   educational-num  48789 non-null  int64
 5   marital-status   48789 non-null  str
 6   occupation       48789 non-null  str
 7   relationship     48789 non-null  str
 8   race             48789 non-null  str
 9   gender           48789 non-null  str
 10  capital-gain     48789 non-null  int64
 11  capital-loss     48789 non-null  int64
 12  hours-per-week   48789 non-null  int64
 13  native-country   48789 non-null  str
 14  income           48789 non-null  int64
dtypes: int64(7), str(8)
memory usage: 5.6 MB

In [29]:
df_count_norm.to_csv('../datos/procesados/adult_count_norm.csv')

# HASH ENCODING

In [15]:
col_categoricas = ['workclass', 'education', 'marital-status', "occupation", "relationship", "race", "gender", "native-country"]
df_hash_8 = HashingEncoder(cols=col_categoricas, n_components=8).fit_transform(df)
df_hash_16 = HashingEncoder(cols=col_categoricas, n_components=16).fit_transform(df)
df_hash_32 = HashingEncoder(cols=col_categoricas, n_components=16).fit_transform(df)

In [16]:
df_hash_8.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income
0,0,3,0,0,1,1,2,1,25,226802,7,0,0,40,0
1,1,1,1,2,0,1,2,0,38,89814,9,0,0,50,0
2,1,1,0,1,0,3,2,0,28,336951,12,0,0,40,1
3,1,1,0,1,1,1,2,1,44,160323,10,7688,0,40,1
4,1,3,0,0,0,0,2,2,18,103497,10,0,0,30,0

In [17]:
df_hash_8.info()

<class 'pandas.DataFrame'>
RangeIndex: 48789 entries, 0 to 48788
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   col_0            48789 non-null  int64
 1   col_1            48789 non-null  int64
 2   col_2            48789 non-null  int64
 3   col_3            48789 non-null  int64
 4   col_4            48789 non-null  int64
 5   col_5            48789 non-null  int64
 6   col_6            48789 non-null  int64
 7   col_7            48789 non-null  int64
 8   age              48789 non-null  int64
 9   fnlwgt           48789 non-null  int64
 10  educational-num  48789 non-null  int64
 11  capital-gain     48789 non-null  int64
 12  capital-loss     48789 non-null  int64
 13  hours-per-week   48789 non-null  int64
 14  income           48789 non-null  int64
dtypes: int64(15)
memory usage: 5.6 MB

In [18]:
df_hash_16.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_13,col_14,col_15,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income
0,0,3,0,0,0,0,1,0,0,0,...,1,1,1,25,226802,7,0,0,40,0
1,1,1,0,0,0,0,2,0,0,0,...,1,0,0,38,89814,9,0,0,50,0
2,1,1,0,0,0,0,2,0,0,0,...,3,0,0,28,336951,12,0,0,40,1
3,1,1,0,0,0,0,1,1,0,0,...,1,1,0,44,160323,10,7688,0,40,1
4,1,3,0,0,0,0,2,2,0,0,...,0,0,0,18,103497,10,0,0,30,0

In [19]:
df_hash_16.info()

<class 'pandas.DataFrame'>
RangeIndex: 48789 entries, 0 to 48788
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   col_0            48789 non-null  int64
 1   col_1            48789 non-null  int64
 2   col_2            48789 non-null  int64
 3   col_3            48789 non-null  int64
 4   col_4            48789 non-null  int64
 5   col_5            48789 non-null  int64
 6   col_6            48789 non-null  int64
 7   col_7            48789 non-null  int64
 8   col_8            48789 non-null  int64
 9   col_9            48789 non-null  int64
 10  col_10           48789 non-null  int64
 11  col_11           48789 non-null  int64
 12  col_12           48789 non-null  int64
 13  col_13           48789 non-null  int64
 14  col_14           48789 non-null  int64
 15  col_15           48789 non-null  int64
 16  age              48789 non-null  int64
 17  fnlwgt           48789 non-null  int64
 18  educational-num  48789 non-null  int64
 19  capital-gain     48789 non-null  int64
 20  capital-loss     48789 non-null  int64
 21  hours-per-week   48789 non-null  int64
 22  income           48789 non-null  int64
dtypes: int64(23)
memory usage: 8.6 MB

In [20]:
df_hash_32.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_13,col_14,col_15,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income
0,0,3,0,0,0,0,1,0,0,0,...,1,1,1,25,226802,7,0,0,40,0
1,1,1,0,0,0,0,2,0,0,0,...,1,0,0,38,89814,9,0,0,50,0
2,1,1,0,0,0,0,2,0,0,0,...,3,0,0,28,336951,12,0,0,40,1
3,1,1,0,0,0,0,1,1,0,0,...,1,1,0,44,160323,10,7688,0,40,1
4,1,3,0,0,0,0,2,2,0,0,...,0,0,0,18,103497,10,0,0,30,0

In [21]:
df_hash_32.info()

<class 'pandas.DataFrame'>
RangeIndex: 48789 entries, 0 to 48788
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   col_0            48789 non-null  int64
 1   col_1            48789 non-null  int64
 2   col_2            48789 non-null  int64
 3   col_3            48789 non-null  int64
 4   col_4            48789 non-null  int64
 5   col_5            48789 non-null  int64
 6   col_6            48789 non-null  int64
 7   col_7            48789 non-null  int64
 8   col_8            48789 non-null  int64
 9   col_9            48789 non-null  int64
 10  col_10           48789 non-null  int64
 11  col_11           48789 non-null  int64
 12  col_12           48789 non-null  int64
 13  col_13           48789 non-null  int64
 14  col_14           48789 non-null  int64
 15  col_15           48789 non-null  int64
 16  age              48789 non-null  int64
 17  fnlwgt           48789 non-null  int64
 18  educational-num  48789 non-null  int64
 19  capital-gain     48789 non-null  int64
 20  capital-loss     48789 non-null  int64
 21  hours-per-week   48789 non-null  int64
 22  income           48789 non-null  int64
dtypes: int64(23)
memory usage: 8.6 MB

In [22]:
df_hash_8.to_csv('../datos/procesados/adult_hash_8.csv')
df_hash_16.to_csv('../datos/procesados/adult_hash_16.csv')
df_hash_32.to_csv('../datos/procesados/adult_hash_32.csv')